version: "3.5"

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.220.0/28

volumes:
    data_mysql:

services:
    mysql:
        env_file:
            - .env
        image: percona:5.5-stretch
        container_name: n_mysql
        volumes:
            - "./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf"
            - data_mysql:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - internal

    adminer:
        image: adminer
        container_name: adminer
        links:
            - mysql:mysql
        ports:
            - 8080:8080
        networks:
            - internal

    nginx:
        env_file:
            - .env
        image: nginx:1.17.4
        container_name: n_nginx
        volumes:
            - "./:/var/www/netcat:rw"
            - "./docker/nginx/netcat.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - 80:80
        networks:
            - internal
        depends_on:
            - app
    app:
        env_file:
            - .env
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
            args:
                - APP_ENV
                - TIMEZONE
        container_name: n_app
        volumes:
            - "./www/netcat:/var/www/netcat:rw"
        networks:
            - internal